### ISSUE TITLE
The bundle is broken

### ISSUE THREAD

**Issue by ahanriat** [llaine/hans-landa#15]
We are missing dependencies in the dist
<img width="728" alt="Screenshot 2020-03-10 at 14 19 12" src="https://user-images.githubusercontent.com/1374161/76316080-39c7a800-62da-11ea-8c50-839cb2cd630b.png">

**Comment by llaine** [comment]
The https://github.com/llaine/hans-landa/pull/14/files added some changes into the `dist` with the `@actions/core`.
